name: easy_storybook
description: EasyStorybook Project
version: 1.0.8
homepage: https://github.com/FightTech-VN/easy_storybook

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  storybook_flutter: ^0.14.1
  dio: ^5.0.1
  shared_preferences: ^2.0.18

  widgetbook: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
