name: easy_storybook
description: EasyStorybook Project
version: 1.0.1
homepage: https://tech.fighttech.vn

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  storybook_flutter: ^0.11.1
  dio: ^4.0.6
  shared_preferences: ^2.0.13

  widgetbook: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
